---
title: "Classificazione su dataset LIWC con re-training"
output:
  html_document:
    df_print: paged
---

Prestazioni classificazione su dataset di saggi LIWC (con re-training)

```{r setup, include=FALSE}
# library setup, depedencies are handled by R
library(caret) # for param tuning
library(e1071) # for normality adjustment
library(LiblineaR)
library(plyr)
library(kableExtra)
options(knitr.table.format = "html")

initial.options <- commandArgs(trailingOnly = FALSE)
file.arg.name <- "--file="
script.name <- sub(file.arg.name, "", initial.options[grep(file.arg.name, initial.options)])
script.basename <- dirname(script.name)
path <- paste(getwd(),script.basename,sep="/")

classification <- function(class_num,dataset) {
  excluded_predictors_new <- c(excluded_predictors,class[-class_num])
  d <- dataset[ , !(names(dataset) %in% excluded_predictors_new)]
  
  set.seed(1234)
  trainIndex <- createDataPartition(d[,class[class_num]], p=0.70, list=FALSE)
  data_train <- d[ trainIndex,]
  data_test <- d[-trainIndex,]
    
  x_train <- data_train[, !(names(data_train) %in% class[class_num])]
  y_train <- data_train[,class[class_num]]
  x_test <- data_test[, !(names(data_test) %in% class[class_num])]
  y_test <- data_test[,class[class_num]]
  
  tryTypes=c(0:7)
  tryCosts=c(0.01,0.05,0.10,0.25,0.5)
  bestCost=NA
  bestAcc=0
  bestType=NA
  
  for(ty in tryTypes){
  for(co in tryCosts){
    
    set.seed(1234)
    model <- LiblineaR(data=x_train,target=y_train,type=ty,cost=co,verbose=FALSE)

    predictions <- predict(model, x_test)
    cm <- confusionMatrix(predictions$predictions, y_test, positive = 'y')
    acc <- cm$overall[1]
    
    if(acc>bestAcc){
      bestCost=co
      bestAcc=acc
      bestType=ty
  } } }
  
  set.seed(1234)
  model <- LiblineaR(data=x_train,target=y_train,type=bestType,cost=bestCost,verbose=FALSE)
  
  p <- predict(model,x_test)
  pred = p$predictions
  
  #y <- revalue(factor(y_test, levels = c ("y", "n")), c("y"="H", "n"="L"))
  cm <- confusionMatrix(pred, y_test, positive = 'y')
  
  accuracy <- round(cm$overall[1], digits = 3)
  rmse <- round(RMSE(as.numeric(predictions$predictions),as.numeric(y_test)),3)
  mae <- round(MAE(as.numeric(predictions$predictions),as.numeric(y_test)),3)
  best_param <- paste('Model:',bestType,'C:',bestCost,sep=' ')
  return(c(accuracy,mae,rmse,best_param))
}
```

```{r}
csv_file <- paste(path,'feature_texts_liwc_ngrams(100).csv',sep="/")
  
# comma delimiter
dataset <- read.csv(csv_file, header = TRUE, sep=",")

# list of predictor vars by name
excluded_predictors <- c('ID')

dataset <- dataset[ , !(names(dataset) %in% excluded_predictors)]
# if any, exclude rows with Na, NaN and Inf (missing values)
dataset <- na.omit(dataset)

accuracies <- list()
maes <- list()
rmses <- list()

class <- c('cOPN','cCON','cEXT','cAGR','cNEU')

for(n in 1:5){
  result = classification(n,dataset)
  accuracies[class[n]] <- as.numeric(result[1])
  maes[class[n]] <- as.numeric(result[2])
  rmses[class[n]] <- as.numeric(result[3])
  print(paste(class[n],result[4],sep=' '))
}
```

ACCURACY

```{r}
accuracies_df <- data.frame(matrix(unlist(accuracies), nrow=1, byrow=T))
colnames(accuracies_df) = names(accuracies)
kable(accuracies_df, caption = 'Accuracy LIWC Dataset')%>%
        kable_styling("striped") %>%
        add_header_above(c("Accuracy" = 5))
```

MAE

```{r}
maes_df <- data.frame(matrix(unlist(maes), nrow=1, byrow=T))
colnames(maes_df) = names(maes)
kable(maes_df, caption = 'MAE LIWC Dataset')%>%
        kable_styling("striped") %>%
        add_header_above(c("MAE" = 5))
```

RMSE

```{r}
rmse_df <- data.frame(matrix(unlist(rmses), nrow=1, byrow=T))
colnames(rmse_df) = names(rmses)
kable(rmse_df, caption = 'RMSE LIWC Dataset')%>%
        kable_styling("striped") %>%
        add_header_above(c("RMSE" = 5))
```